version: '3.9'
services:
  dev-finder-db:
    image: postgres
    restart: always
    container_name: YOUR_CONTAINER_NAME_HERE
    ports:
      - 5000:5432
    environment:
      POSTGRES_PASSWORD: YOUR_PASSWORD_HERE
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: